# Generated by Django 5.1.7 on 2025-04-14 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='designation',
            new_name='surface',
        ),
    ]
